package com.example.tastecode.ui.utils

object Keywords {

    val recipeType = listOf<String>(
        "Apple dessert recipes" ,
        "Beef slow cooker",
        "Black bean recipes",
        "Blue cheese recipes",
        "Breakfast muffins",
        "Breakfast pancakes",
        "Breakfast smoothies",
        "Broad bean recipes",
        "Cheddar recipes",
        "Chicken breast recipes",
        "Chicken casseroles",
        "Chicken mince recipes",
        "Chicken thigh recipes",
        "Chilli con carne recipes",
        "Chocolate desserts",
        "Diced beef recipes",
        "Dinner-to-lunch-recipes",
        "Easy dessert recipes",
        "Easy vegan recipes",
        "Easy vegetarian recipes",
        "Family lunch recipes",
        "Fish pie recipes",
        "Goat's cheese recipes",
        "Halloumi recipes",
        "Healthy dessert recipes",
        "Healthy fish recipes",
        "Healthy lunch recipes",
        "Healthy packed lunches",
        "Kidney bead recipes",
        "Lamb chop recipes",
        "One pot recipes",
        "Overnight oat recipes",
        "Pasta bake recipes",
        "Pasta recipes",
        "Pasta salad recipes",
        "Pork chop recipes",
        "Quick lunch recipes",
        "Quick pasta recipes",
        "Runner bean recipes",
        "Seafood paella recipes",
        "Spaghetti recipes",
        "Vegan dinner recipes",
        "Vegan pasta recipes",
        "Vegan soup recipes",
        "Vegetarian dinners",
        "Vegetarian pasta recipes",
        "Vegetarian slow cooker",
        "White fish recipes"
    )


    val difficultyList = listOf<String>(
        "A challenge",
        "Easy",
        "More effort",
    )


    val preparationtimeList = listOf<String>(
        "1 hour",
        "2 mins",
        "5 mins",
        "7 mins",
        "8 mins",
        "10 mins",
        "12 mins",
        "15 mins",
        "17 mins",
        "18 mins",
        "20 mins",
        "22 mins",
        "25 mins",
        "30 mins",
        "35 mins",
        "40 mins",
        "45 mins",
        "50 mins",
        "55 mins",
        "1 hour and 10 mins",
        "1 hour and 15 mins",
        "1 hour and 20 mins",
        "1 hour and 25 mins",
        "1 hour and 30 mins",
        "1 hour and 40 mins",
        "1 hour and 45 mins",
        "1 hour and 50 mins",
        "2 hours",
        "2 hours and 15 mins",
        "2 hours and 20 mins",
        "2 hours and 30 mins",
        "3 hours",
        "3 hours and 30 mins",
        "4 hours",
        "4 hours and 30 mins",
        "6 hours and 35 mins",
        "7 hours and 30 mins",
        "8 hours",
        "No Time"
    )
}